import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BadgeDollarSign, Ban, CheckCircle2, CreditCard, Download, ShieldCheck, Users } from 'lucide-react';
import { api, errorMessage } from '../lib/api';
import { useAuth } from '../lib/auth';
import { EmptyState, Loading, Notice, PageHeader, StatusBadge } from '../components/ui';

const money = (value: number) => `NT$${value.toLocaleString('zh-TW')}`;

export function BillingPage() {
  const { session } = useAuth();
  const plans = useQuery({ queryKey: ['billing-plans'], queryFn: async () => (await api.get('/billing/plans')).data });
  const orders = useQuery({ queryKey: ['billing-orders'], queryFn: async () => (await api.get('/billing/orders')).data });
  const releases = useQuery({ queryKey: ['releases'], queryFn: async () => (await api.get('/downloads/releases')).data });
  const usage = useQuery({ queryKey: ['download-usage'], queryFn: async () => (await api.get('/downloads/usage')).data });
  const checkout = useMutation({ mutationFn: async (plan: string) => (await api.post('/billing/checkout', { plan })).data, onSuccess: (data) => window.location.assign(data.checkoutUrl) });
  const download = useMutation({ mutationFn: async (releaseId: string) => (await api.post('/downloads/request', { releaseId })).data, onSuccess: (data) => window.location.assign(data.url) });
  return <><PageHeader title="方案與授權" description={`目前方案：${session?.workspace.plan ?? 'TRIAL'}。工作區 OWNER 只代表管理權，付費權益由此方案決定。`} />
    {checkout.error && <Notice type="error">{errorMessage(checkout.error)}</Notice>}
    <div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-4">{plans.isLoading ? <Loading /> : plans.data?.items.filter((plan: any) => plan.key !== 'TRIAL').map((plan: any) => <article key={plan.key} className={`card p-5 ${session?.workspace.plan === plan.key ? 'ring-2 ring-brand-500' : ''}`}><p className="text-xs font-black tracking-widest text-brand-600">{plan.key}</p><h2 className="mt-2 text-xl font-black text-ink">{plan.name}</h2><p className="mt-3 text-3xl font-black text-ink">{money(plan.priceTwd)}</p><p className="mt-1 text-xs text-slate-400">一次買斷，含 {plan.supportMonths} 個月更新</p><div className="mt-4 space-y-2 text-sm text-slate-600">{plan.features.map((feature: string) => <p key={feature} className="flex gap-2"><CheckCircle2 size={16} className="mt-0.5 text-brand-600" />{feature}</p>)}</div><p className="mt-4 text-xs text-slate-400">{plan.seats} 使用者 · {plan.devices} 裝置 · {plan.downloadQuota} 次安裝包下載</p><button className="btn-primary mt-5 w-full" disabled={checkout.isPending || session?.workspace.plan === plan.key} onClick={() => checkout.mutate(plan.key)}><CreditCard size={16} />{session?.workspace.plan === plan.key ? '目前方案' : '前往安全付款'}</button></article>)}</div>
    <section className="card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-ink">Windows / macOS 一鍵安裝包</h2><p className="mt-1 text-xs text-slate-400">下載額度：{usage.data?.quota == null ? 'SUPERADMIN 無產品配額' : `${usage.data?.used ?? 0} / ${usage.data?.quota ?? 0}`}。每個連結 10 分鐘有效且只能使用一次。</p></div>{download.error && <div className="p-4"><Notice type="error">{errorMessage(download.error)}</Notice></div>}{releases.isLoading ? <Loading /> : !releases.data?.items.length ? <EmptyState icon={<Download />} title="尚未發布安裝包" description="SUPERADMIN 發布 Release 並記錄 SHA-256 後，符合方案的使用者才會看到下載按鈕。" /> : <div className="table-wrap"><table className="table"><thead><tr><th>平台</th><th>版本</th><th>最低方案</th><th>大小</th><th>SHA-256</th><th></th></tr></thead><tbody>{releases.data.items.map((release: any) => <tr key={release.id}><td>{release.platform}</td><td>{release.version}</td><td>{release.minimumPlan}</td><td>{(Number(release.size)/1024/1024).toFixed(2)} MB</td><td><code className="text-[10px]">{release.sha256.slice(0,16)}…</code></td><td><button className="btn-secondary !px-3 !py-2" disabled={!release.eligible || download.isPending} onClick={() => download.mutate(release.id)}><Download size={15}/>{release.eligible ? '產生一次性連結' : '方案不足'}</button></td></tr>)}</tbody></table></div>}</section>
    <section className="card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-ink">付款紀錄</h2></div>{orders.isLoading ? <Loading /> : !orders.data?.items.length ? <EmptyState icon={<BadgeDollarSign />} title="尚無付款紀錄" description="完成付款後，Webhook 會自動升級工作區並開放對應安裝包。" /> : <div className="table-wrap"><table className="table"><thead><tr><th>方案</th><th>金額</th><th>狀態</th><th>時間</th></tr></thead><tbody>{orders.data.items.map((order: any) => <tr key={order.id}><td>{order.plan}</td><td>{money(order.amountTwd)}</td><td><StatusBadge status={order.status} /></td><td>{new Date(order.createdAt).toLocaleString('zh-TW')}</td></tr>)}</tbody></table></div>}</section>
  </>;
}

export function AdminPage() {
  const { session } = useAuth(); const client = useQueryClient();
  const [releaseForm, setReleaseForm] = useState<{ version: string; platform: 'WINDOWS'|'MACOS'; minimumPlan: string; file: File | null }>({ version: '1.0.0', platform: 'WINDOWS', minimumPlan: 'STARTER', file: null });
  const overview = useQuery({ queryKey: ['admin-overview'], queryFn: async () => (await api.get('/admin/overview')).data, enabled: session?.user.platformRole === 'SUPERADMIN' });
  const users = useQuery({ queryKey: ['admin-users'], queryFn: async () => (await api.get('/admin/users')).data, enabled: session?.user.platformRole === 'SUPERADMIN' });
  const workspaces = useQuery({ queryKey: ['admin-workspaces'], queryFn: async () => (await api.get('/admin/workspaces')).data, enabled: session?.user.platformRole === 'SUPERADMIN' });
  const payments = useQuery({ queryKey: ['admin-payments'], queryFn: async () => (await api.get('/admin/payments')).data, enabled: session?.user.platformRole === 'SUPERADMIN' });
  const audit = useQuery({ queryKey: ['admin-audit'], queryFn: async () => (await api.get('/admin/audit')).data, enabled: session?.user.platformRole === 'SUPERADMIN' });
  const releases = useQuery({ queryKey: ['admin-releases'], queryFn: async () => (await api.get('/admin/releases')).data, enabled: session?.user.platformRole === 'SUPERADMIN' });
  const updateUser = useMutation({ mutationFn: ({ id, body }: any) => api.patch(`/admin/users/${id}`, body), onSuccess: () => client.invalidateQueries({ queryKey: ['admin-users'] }) });
  const updateWorkspace = useMutation({ mutationFn: ({ id, body }: any) => api.patch(`/admin/workspaces/${id}`, body), onSuccess: () => client.invalidateQueries({ queryKey: ['admin-workspaces'] }) });
  const publishRelease = useMutation({ mutationFn: async () => { const form = new FormData(); form.append('version', releaseForm.version); form.append('platform', releaseForm.platform); form.append('minimumPlan', releaseForm.minimumPlan); if (releaseForm.file) form.append('file', releaseForm.file); return api.post('/admin/releases', form); }, onSuccess: () => client.invalidateQueries({ queryKey: ['admin-releases'] }) });
  if (session?.user.platformRole !== 'SUPERADMIN') return <Notice type="error">需要平台 SUPERADMIN 權限。</Notice>;
  if (overview.isLoading) return <Loading label="載入平台後台" />;
  const cards = [['帳號', overview.data.users, Users], ['工作區', overview.data.workspaces, ShieldCheck], ['已付款', overview.data.paidOrders, BadgeDollarSign], ['已停權', overview.data.suspendedUsers, Ban]] as const;
  return <><PageHeader title="平台管理後台" description="SUPERADMIN 專用：管理帳號、工作區、方案、停權、付款與平台稽核。" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon]) => <div className="card p-5" key={label}><Icon className="text-brand-600" /><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-black text-ink">{value}</p></div>)}</div>
    <section className="card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">帳號管理</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>帳號</th><th>平台角色</th><th>狀態</th><th>驗證</th><th></th></tr></thead><tbody>{users.data?.items.map((user: any) => <tr key={user.id}><td><p className="font-bold">{user.name}</p><p className="text-xs text-slate-400">{user.email}</p></td><td>{user.platformRole}</td><td>{user.status}</td><td>{user.emailVerifiedAt ? '已驗證' : '未驗證'}</td><td>{user.id !== session.user.id && <button className="btn-secondary !px-3 !py-2" onClick={() => updateUser.mutate({ id: user.id, body: { status: user.status === 'SUSPENDED' ? 'ACTIVE' : 'SUSPENDED' } })}>{user.status === 'SUSPENDED' ? '恢復' : '停權'}</button>}</td></tr>)}</tbody></table></div></section>
    <section className="card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">工作區與方案</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>工作區</th><th>擁有者</th><th>方案</th><th>用量</th><th>下載額度</th><th></th></tr></thead><tbody>{workspaces.data?.items.map((workspace: any) => <tr key={workspace.id}><td>{workspace.name}</td><td>{workspace.members[0]?.user.email ?? '—'}</td><td><select className="input min-w-40" value={workspace.plan} onChange={(event) => updateWorkspace.mutate({ id: workspace.id, body: { plan: event.target.value } })}>{['TRIAL','STARTER','PROFESSIONAL','BUSINESS','ENTERPRISE'].map((plan) => <option key={plan}>{plan}</option>)}</select></td><td>{workspace._count.sourceFiles} 檔</td><td>{workspace.downloadQuota}</td><td><button className="btn-secondary !px-3 !py-2" onClick={() => updateWorkspace.mutate({ id: workspace.id, body: { suspended: !workspace.suspendedAt } })}>{workspace.suspendedAt ? '恢復' : '停用'}</button></td></tr>)}</tbody></table></div></section>
    <section className="card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">最近付款</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>帳號</th><th>工作區</th><th>方案</th><th>金額</th><th>狀態</th></tr></thead><tbody>{payments.data?.items.slice(0, 30).map((item: any) => <tr key={item.id}><td>{item.user.email}</td><td>{item.workspace.name}</td><td>{item.plan}</td><td>{money(item.amountTwd)}</td><td>{item.status}</td></tr>)}</tbody></table></div></section>
    <section className="card mt-6 p-5"><h2 className="font-bold">發布一鍵安裝包</h2><p className="mt-1 text-xs text-slate-400">ZIP 會儲存在私有資料庫物件中；系統自動計算 SHA-256，使用者只能透過短效一次性 token 下載。</p>{publishRelease.error && <div className="mt-3"><Notice type="error">{errorMessage(publishRelease.error)}</Notice></div>}<div className="mt-4 grid gap-3 md:grid-cols-4"><input className="input" value={releaseForm.version} onChange={(event) => setReleaseForm({ ...releaseForm, version: event.target.value })} placeholder="1.0.0"/><select className="input" value={releaseForm.platform} onChange={(event) => setReleaseForm({ ...releaseForm, platform: event.target.value as 'WINDOWS'|'MACOS' })}><option>WINDOWS</option><option>MACOS</option></select><select className="input" value={releaseForm.minimumPlan} onChange={(event) => setReleaseForm({ ...releaseForm, minimumPlan: event.target.value })}>{['STARTER','PROFESSIONAL','BUSINESS','ENTERPRISE'].map((plan) => <option key={plan}>{plan}</option>)}</select><input className="input" type="file" accept=".zip" onChange={(event) => setReleaseForm({ ...releaseForm, file: event.target.files?.[0] ?? null })}/></div><button className="btn-primary mt-4" disabled={!releaseForm.file || publishRelease.isPending} onClick={() => publishRelease.mutate()}>發布 Release</button><div className="mt-5 divide-y divide-slate-100">{releases.data?.items.map((release: any) => <div className="flex flex-wrap justify-between gap-2 py-3 text-sm" key={release.id}><span className="font-bold">{release.platform} v{release.version} · {release.minimumPlan}</span><code className="text-xs text-slate-400">{release.sha256}</code></div>)}</div></section>
    <section className="card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">平台稽核</h2></div><div className="divide-y divide-slate-100">{audit.data?.items.slice(0, 50).map((item: any) => <div key={item.id} className="px-5 py-3 text-sm"><span className="font-mono font-bold">{item.action}</span><span className="ml-3 text-slate-400">{item.actor?.email ?? 'System'} · {new Date(item.createdAt).toLocaleString('zh-TW')}</span></div>)}</div></section>
  </>;
}
