import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BadgeDollarSign, Ban, CheckCircle2, CreditCard, ShieldCheck, Users } from 'lucide-react';
import { api, errorMessage } from '../lib/api';
import { useAuth } from '../lib/auth';
import { EmptyState, Loading, Notice, PageHeader, StatusBadge } from '../components/ui';

const money = (value: number) => `NT$${value.toLocaleString('zh-TW')}`;

export function BillingPage() {
  const { session } = useAuth();
  const plans = useQuery({ queryKey: ['billing-plans'], queryFn: async () => (await api.get('/billing/plans')).data });
  const orders = useQuery({ queryKey: ['billing-orders'], queryFn: async () => (await api.get('/billing/orders')).data });
  const checkout = useMutation({ mutationFn: async (plan: string) => (await api.post('/billing/checkout', { plan })).data, onSuccess: (data) => window.location.assign(data.checkoutUrl) });
  return <><PageHeader title="方案與授權" description={`目前方案：${session?.workspace.plan ?? 'TRIAL'}。工作區 OWNER 只代表管理權，付費權益由此方案決定。`} />
    {checkout.error && <Notice type="error">{errorMessage(checkout.error)}</Notice>}
    <div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-4">{plans.isLoading ? <Loading /> : plans.data?.items.filter((plan: any) => plan.key !== 'TRIAL').map((plan: any) => <article key={plan.key} className={`card p-5 ${session?.workspace.plan === plan.key ? 'ring-2 ring-brand-500' : ''}`}><p className="text-xs font-black tracking-widest text-brand-600">{plan.key}</p><h2 className="mt-2 text-xl font-black text-ink">{plan.name}</h2><p className="mt-3 text-3xl font-black text-ink">{money(plan.priceTwd)}</p><p className="mt-1 text-xs text-slate-400">一次買斷，含 {plan.supportMonths} 個月更新</p><div className="mt-4 space-y-2 text-sm text-slate-600">{plan.features.map((feature: string) => <p key={feature} className="flex gap-2"><CheckCircle2 size={16} className="mt-0.5 text-brand-600" />{feature}</p>)}</div><p className="mt-4 text-xs text-slate-400">{plan.seats} 使用者 · {plan.devices} 裝置 · {plan.downloadQuota} 次安裝包下載</p><button className="btn-primary mt-5 w-full" disabled={checkout.isPending || session?.workspace.plan === plan.key} onClick={() => checkout.mutate(plan.key)}><CreditCard size={16} />{session?.workspace.plan === plan.key ? '目前方案' : '前往安全付款'}</button></article>)}</div>
    <section className="card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-ink">付款紀錄</h2></div>{orders.isLoading ? <Loading /> : !orders.data?.items.length ? <EmptyState icon={<BadgeDollarSign />} title="尚無付款紀錄" description="完成付款後，Webhook 會自動升級工作區並開放對應安裝包。" /> : <div className="table-wrap"><table className="table"><thead><tr><th>方案</th><th>金額</th><th>狀態</th><th>時間</th></tr></thead><tbody>{orders.data.items.map((order: any) => <tr key={order.id}><td>{order.plan}</td><td>{money(order.amountTwd)}</td><td><StatusBadge status={order.status} /></td><td>{new Date(order.createdAt).toLocaleString('zh-TW')}</td></tr>)}</tbody></table></div>}</section>
  </>;
}

export function AdminPage() {
  const { session } = useAuth(); const client = useQueryClient();
  const overview = useQuery({ queryKey: ['admin-overview'], queryFn: async () => (await api.get('/admin/overview')).data, enabled: session?.user.platformRole === 'SUPERADMIN' });
  const users = useQuery({ queryKey: ['admin-users'], queryFn: async () => (await api.get('/admin/users')).data, enabled: session?.user.platformRole === 'SUPERADMIN' });
  const workspaces = useQuery({ queryKey: ['admin-workspaces'], queryFn: async () => (await api.get('/admin/workspaces')).data, enabled: session?.user.platformRole === 'SUPERADMIN' });
  const payments = useQuery({ queryKey: ['admin-payments'], queryFn: async () => (await api.get('/admin/payments')).data, enabled: session?.user.platformRole === 'SUPERADMIN' });
  const audit = useQuery({ queryKey: ['admin-audit'], queryFn: async () => (await api.get('/admin/audit')).data, enabled: session?.user.platformRole === 'SUPERADMIN' });
  const updateUser = useMutation({ mutationFn: ({ id, body }: any) => api.patch(`/admin/users/${id}`, body), onSuccess: () => client.invalidateQueries({ queryKey: ['admin-users'] }) });
  const updateWorkspace = useMutation({ mutationFn: ({ id, body }: any) => api.patch(`/admin/workspaces/${id}`, body), onSuccess: () => client.invalidateQueries({ queryKey: ['admin-workspaces'] }) });
  if (session?.user.platformRole !== 'SUPERADMIN') return <Notice type="error">需要平台 SUPERADMIN 權限。</Notice>;
  if (overview.isLoading) return <Loading label="載入平台後台" />;
  const cards = [['帳號', overview.data.users, Users], ['工作區', overview.data.workspaces, ShieldCheck], ['已付款', overview.data.paidOrders, BadgeDollarSign], ['已停權', overview.data.suspendedUsers, Ban]] as const;
  return <><PageHeader title="平台管理後台" description="SUPERADMIN 專用：管理帳號、工作區、方案、停權、付款與平台稽核。" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon]) => <div className="card p-5" key={label}><Icon className="text-brand-600" /><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-black text-ink">{value}</p></div>)}</div>
    <section className="card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">帳號管理</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>帳號</th><th>平台角色</th><th>狀態</th><th>驗證</th><th></th></tr></thead><tbody>{users.data?.items.map((user: any) => <tr key={user.id}><td><p className="font-bold">{user.name}</p><p className="text-xs text-slate-400">{user.email}</p></td><td>{user.platformRole}</td><td>{user.status}</td><td>{user.emailVerifiedAt ? '已驗證' : '未驗證'}</td><td>{user.id !== session.user.id && <button className="btn-secondary !px-3 !py-2" onClick={() => updateUser.mutate({ id: user.id, body: { status: user.status === 'SUSPENDED' ? 'ACTIVE' : 'SUSPENDED' } })}>{user.status === 'SUSPENDED' ? '恢復' : '停權'}</button>}</td></tr>)}</tbody></table></div></section>
    <section className="card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">工作區與方案</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>工作區</th><th>擁有者</th><th>方案</th><th>用量</th><th>下載額度</th><th></th></tr></thead><tbody>{workspaces.data?.items.map((workspace: any) => <tr key={workspace.id}><td>{workspace.name}</td><td>{workspace.members[0]?.user.email ?? '—'}</td><td><select className="input min-w-40" value={workspace.plan} onChange={(event) => updateWorkspace.mutate({ id: workspace.id, body: { plan: event.target.value } })}>{['TRIAL','STARTER','PROFESSIONAL','BUSINESS','ENTERPRISE'].map((plan) => <option key={plan}>{plan}</option>)}</select></td><td>{workspace._count.sourceFiles} 檔</td><td>{workspace.downloadQuota}</td><td><button className="btn-secondary !px-3 !py-2" onClick={() => updateWorkspace.mutate({ id: workspace.id, body: { suspended: !workspace.suspendedAt } })}>{workspace.suspendedAt ? '恢復' : '停用'}</button></td></tr>)}</tbody></table></div></section>
    <section className="card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">最近付款</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>帳號</th><th>工作區</th><th>方案</th><th>金額</th><th>狀態</th></tr></thead><tbody>{payments.data?.items.slice(0, 30).map((item: any) => <tr key={item.id}><td>{item.user.email}</td><td>{item.workspace.name}</td><td>{item.plan}</td><td>{money(item.amountTwd)}</td><td>{item.status}</td></tr>)}</tbody></table></div></section>
    <section className="card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">平台稽核</h2></div><div className="divide-y divide-slate-100">{audit.data?.items.slice(0, 50).map((item: any) => <div key={item.id} className="px-5 py-3 text-sm"><span className="font-mono font-bold">{item.action}</span><span className="ml-3 text-slate-400">{item.actor?.email ?? 'System'} · {new Date(item.createdAt).toLocaleString('zh-TW')}</span></div>)}</div></section>
  </>;
}
