import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Braces, Database, FileJson2, Library, Network, Plus, Trash2 } from 'lucide-react';
import { api, errorMessage } from '../lib/api';
import { EmptyState, Loading, Modal, Notice, PageHeader } from '../components/ui';

export function SourcesPage() {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: '', kind: 'UPLOAD' }); const [error, setError] = useState('');
  const sources = useQuery({ queryKey: ['sources'], queryFn: async () => (await api.get('/sources')).data });
  const create = useMutation({ mutationFn: () => api.post('/sources', { ...form, config: {} }), onSuccess: async () => { setOpen(false); setForm({ name: '', kind: 'UPLOAD' }); await client.invalidateQueries({ queryKey: ['sources'] }); }, onError: (err) => setError(errorMessage(err)) });
  const remove = useMutation({ mutationFn: (id: string) => api.delete(`/sources/${id}`), onSuccess: () => client.invalidateQueries({ queryKey: ['sources'] }) });
  const kinds: Record<string, string> = { UPLOAD: '手動多檔上傳', FOLDER: '瀏覽器資料夾上傳', ZIP: 'ZIP 批次上傳' };
  return <><PageHeader title="資料來源" description="只呈現目前可實際執行的來源。雲端連接器需在伺服器配置 OAuth 憑證後，才會開放授權。" action={<button className="btn-primary" onClick={() => setOpen(true)}><Plus size={16} />新增來源</button>} /><section className="card overflow-hidden">{sources.isLoading ? <Loading /> : !sources.data?.items.length ? <EmptyState icon={<Database />} title="尚未建立資料來源" description="可先建立手動上傳、資料夾或 ZIP 來源，再到智慧分析開始處理。" /> : <div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-3">{sources.data.items.map((source: any) => <div key={source.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between"><div className="rounded-lg bg-brand-50 p-2.5 text-brand-700"><Database size={18} /></div><button title="刪除來源" className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600" onClick={() => remove.mutate(source.id)}><Trash2 size={16} /></button></div><p className="mt-4 font-bold text-ink">{source.name}</p><p className="mt-1 text-xs text-slate-500">{kinds[source.kind] ?? source.kind}</p><p className="mt-4 text-[11px] text-slate-400">建立於 {new Date(source.createdAt).toLocaleDateString('zh-TW')}</p></div>)}</div>}</section>
    {open && <Modal title="新增資料來源" onClose={() => setOpen(false)}>{error && <Notice type="error">{error}</Notice>}<form className="space-y-4" onSubmit={(e) => { e.preventDefault(); create.mutate(); }}><div><label className="label">來源名稱</label><input className="input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required minLength={2} /></div><div><label className="label">來源類型</label><select className="input" value={form.kind} onChange={(e) => setForm({ ...form, kind: e.target.value })}>{Object.entries(kinds).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><button className="btn-primary w-full">儲存來源</button></form></Modal>}
  </>;
}

export function ReportTypesPage() {
  const query = useQuery({ queryKey: ['report-types'], queryFn: async () => (await api.get('/report-types')).data });
  return <><PageHeader title="報表分類" description="每個工作區都有獨立分類字典；自訂報表可由欄位模板建立。分類引擎會綜合檔名、工作表名、欄位集合與內容。" /><section className="card p-5">{query.isLoading ? <Loading /> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{query.data?.items.map((item: any) => <div key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-3"><div className="rounded-lg bg-violet-50 p-2 text-violet-700"><FileJson2 size={17} /></div><div><p className="font-bold text-slate-800">{item.name}</p><p className="text-xs font-mono text-slate-400">{item.key}</p></div></div></div>)}</div>}</section></>;
}

type FieldDraft = { key: string; name: string; type: string; required: boolean; uniqueKey: boolean; aliases: string };
const emptyField = (): FieldDraft => ({ key: '', name: '', type: 'text', required: false, uniqueKey: false, aliases: '' });

export function SchemasPage() {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [fields, setFields] = useState<FieldDraft[]>([emptyField()]); const [error, setError] = useState('');
  const schemas = useQuery({ queryKey: ['schemas'], queryFn: async () => (await api.get('/schemas')).data });
  const create = useMutation({ mutationFn: () => api.post('/schemas', { name, fields: fields.map((field) => ({ ...field, aliases: field.aliases.split(',').map((value) => value.trim()).filter(Boolean) })) }), onSuccess: async () => { setOpen(false); setName(''); setFields([emptyField()]); await client.invalidateQueries({ queryKey: ['schemas'] }); }, onError: (err) => setError(errorMessage(err)) });
  const updateField = (index: number, patch: Partial<FieldDraft>) => setFields((current) => current.map((field, position) => position === index ? { ...field, ...patch } : field));
  return <><PageHeader title="欄位模板" description="動態 Schema 不會強迫所有報表共用固定欄位。可設定欄位型態、必填、組合唯一鍵與別名。" action={<button className="btn-primary" onClick={() => setOpen(true)}><Plus size={16} />建立模板</button>} /><section className="card overflow-hidden">{schemas.isLoading ? <Loading /> : !schemas.data?.items.length ? <EmptyState icon={<Braces />} title="尚無欄位模板" description="建立自訂企業報表的第一組標準欄位。" /> : <div className="divide-y divide-slate-100">{schemas.data.items.map((schema: any) => <div className="px-5 py-4" key={schema.id}><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-bold text-ink">{schema.name}</p><p className="mt-1 text-xs text-slate-400">版本 {schema.version} · {schema.reportType?.name ?? '自訂報表'}</p></div><span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-bold text-brand-700">{schema.fields.length} 欄</span></div><div className="mt-3 flex flex-wrap gap-2">{schema.fields.map((field: any) => <span key={field.id} className="rounded-lg border border-slate-200 px-2.5 py-1 text-xs text-slate-600">{field.name} · {field.type}{field.required ? ' · 必填' : ''}{field.uniqueKey ? ' · KEY' : ''}</span>)}</div></div>)}</div>}</section>
    {open && <Modal title="建立動態欄位模板" onClose={() => setOpen(false)} wide>{error && <Notice type="error">{error}</Notice>}<div><label className="label">模板名稱</label><input className="input" value={name} onChange={(e) => setName(e.target.value)} required /></div><div className="mt-5 space-y-3">{fields.map((field, index) => <div key={index} className="rounded-xl border border-slate-200 p-4"><div className="grid gap-3 sm:grid-cols-3"><input className="input" value={field.name} onChange={(e) => updateField(index, { name: e.target.value })} placeholder="顯示名稱" /><input className="input font-mono" value={field.key} onChange={(e) => updateField(index, { key: e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, '') })} placeholder="field_key" /><select className="input" value={field.type} onChange={(e) => updateField(index, { type: e.target.value })}>{['text', 'integer', 'decimal', 'money', 'date', 'datetime', 'percentage', 'boolean', 'email', 'phone', 'option', 'custom'].map((type) => <option key={type}>{type}</option>)}</select></div><input className="input mt-3" value={field.aliases} onChange={(e) => updateField(index, { aliases: e.target.value })} placeholder="別名，以逗號分隔" /><div className="mt-3 flex items-center gap-5 text-sm text-slate-600"><label><input type="checkbox" checked={field.required} onChange={(e) => updateField(index, { required: e.target.checked })} /> 必填</label><label><input type="checkbox" checked={field.uniqueKey} onChange={(e) => updateField(index, { uniqueKey: e.target.checked })} /> 唯一鍵</label>{fields.length > 1 && <button className="ml-auto text-rose-600" onClick={() => setFields(fields.filter((_, position) => position !== index))}>移除</button>}</div></div>)}<button className="btn-secondary" onClick={() => setFields([...fields, emptyField()])}><Plus size={15} />新增欄位</button></div><button className="btn-primary mt-6 w-full" onClick={() => create.mutate()} disabled={!name || fields.some((field) => !field.name || !field.key)}>儲存欄位模板</button></Modal>}
  </>;
}

export function TemplatesPage() {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [config, setConfig] = useState('{\n  "headerRow": 1,\n  "ignoreRows": [],\n  "fieldMappings": {}\n}'); const [error, setError] = useState('');
  const templates = useQuery({ queryKey: ['templates'], queryFn: async () => (await api.get('/templates')).data });
  const create = useMutation({ mutationFn: () => api.post('/templates', { name, config: JSON.parse(config) }), onSuccess: async () => { setOpen(false); setName(''); await client.invalidateQueries({ queryKey: ['templates'] }); }, onError: (err) => setError(errorMessage(err)) });
  return <><PageHeader title="解析模板" description="保存表頭位置、資料範圍、欄位映射、小計與清洗規則。每次更新都以版本保存，便於回溯。" action={<button className="btn-primary" onClick={() => setOpen(true)}><Plus size={16} />建立解析模板</button>} /><section className="card overflow-hidden">{templates.isLoading ? <Loading /> : !templates.data?.items.length ? <EmptyState icon={<Library />} title="尚無解析模板" description="完成一次人工確認後可保存同版型規則，或手動建立第一版。" /> : <div className="table-wrap"><table className="table"><thead><tr><th>模板</th><th>報表類型</th><th>版本</th><th>套用次數</th><th>成功率</th><th>更新時間</th></tr></thead><tbody>{templates.data.items.map((template: any) => <tr key={template.id}><td className="font-bold text-slate-800">{template.name}</td><td>{template.reportType?.name ?? '自訂'}</td><td>v{template.currentVersion}</td><td>{template.usageCount}</td><td>{template.usageCount ? `${Math.round(template.successCount / template.usageCount * 100)}%` : '—'}</td><td>{new Date(template.updatedAt).toLocaleString('zh-TW')}</td></tr>)}</tbody></table></div>}</section>
    {open && <Modal title="建立解析模板" onClose={() => setOpen(false)}>{error && <Notice type="error">{error}</Notice>}<div><label className="label">模板名稱</label><input className="input" value={name} onChange={(e) => setName(e.target.value)} /></div><div className="mt-4"><label className="label">規則 JSON</label><textarea className="input min-h-52 font-mono text-xs" value={config} onChange={(e) => setConfig(e.target.value)} /></div><button className="btn-primary mt-5 w-full" onClick={() => { try { JSON.parse(config); create.mutate(); } catch { setError('規則 JSON 格式錯誤'); } }} disabled={!name}>建立版本 1</button></Modal>}
  </>;
}

export function RulesPage() {
  const client = useQueryClient(); const [selected, setSelected] = useState<any>(null); const [operations, setOperations] = useState('[]'); const [error, setError] = useState('');
  const projects = useQuery({ queryKey: ['projects'], queryFn: async () => (await api.get('/projects', { params: { pageSize: 100 } })).data });
  const save = useMutation({ mutationFn: () => api.patch(`/projects/${selected.id}`, { config: { ...(selected.config ?? {}), operations: JSON.parse(operations) } }), onSuccess: async () => { setSelected(null); await client.invalidateQueries({ queryKey: ['projects'] }); }, onError: (err) => setError(errorMessage(err)) });
  return <><PageHeader title="整合規則" description="規則依序執行，可組合 Append、Join、Lookup、Group、Split 與 Transform；去重支援單一或多欄組合鍵。" /><section className="card overflow-hidden">{projects.isLoading ? <Loading /> : !projects.data?.items.length ? <EmptyState icon={<Network />} title="尚無可設定專案" description="先建立整合專案，再保存其資料處理管線。" /> : <div className="divide-y divide-slate-100">{projects.data.items.map((project: any) => <button key={project.id} className="flex w-full items-center justify-between px-5 py-4 text-left hover:bg-slate-50" onClick={() => { setSelected(project); setOperations(JSON.stringify(project.config?.operations ?? [], null, 2)); }}><div><p className="font-bold text-ink">{project.name}</p><p className="mt-1 text-xs text-slate-400">{project.config?.operations?.length ?? 0} 個處理步驟</p></div><Network className="text-brand-600" size={18} /></button>)}</div>}</section>
    {selected && <Modal title={`設定「${selected.name}」規則`} onClose={() => setSelected(null)} wide>{error && <Notice type="error">{error}</Notice>}<p className="mb-3 text-sm leading-6 text-slate-500">每個步驟格式為 <code className="rounded bg-slate-100 px-1">{"{ mode, config }"}</code>。例如 Append：<code className="rounded bg-slate-100 px-1">{"{\"mode\":\"append\",\"config\":{\"name\":\"銷售總表\"}}"}</code></p><textarea className="input min-h-[360px] font-mono text-xs leading-5" value={operations} onChange={(e) => setOperations(e.target.value)} /><button className="btn-primary mt-5 w-full" onClick={() => { try { const parsed = JSON.parse(operations); if (!Array.isArray(parsed)) throw new Error(); save.mutate(); } catch { setError('整合規則必須是有效的 JSON 陣列'); } }}>儲存整合規則</button></Modal>}
  </>;
}
