import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FolderKanban, Plus, Power, Workflow } from 'lucide-react';
import { api, errorMessage } from '../lib/api';
import { EmptyState, Loading, Modal, Notice, PageHeader } from '../components/ui';

const modes = [{ value: 'append', label: 'Append 垂直合併' }, { value: 'join', label: 'Join 關聯合併' }, { value: 'lookup', label: 'Lookup 查找補值' }, { value: 'group', label: 'Group 分組彙總' }, { value: 'split', label: 'Split 拆分' }, { value: 'transform', label: 'Transform 資料轉換' }];

export function ProjectsPage() {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [error, setError] = useState('');
  const [form, setForm] = useState({ name: '', description: '', reportTypeKey: '', schemaId: '', mode: 'append' });
  const projects = useQuery({ queryKey: ['projects'], queryFn: async () => (await api.get('/projects', { params: { pageSize: 100 } })).data });
  const schemas = useQuery({ queryKey: ['schemas'], queryFn: async () => (await api.get('/schemas')).data });
  const create = useMutation({ mutationFn: async () => (await api.post('/projects', { ...form, reportTypeKey: form.reportTypeKey || undefined, schemaId: form.schemaId || undefined })).data, onSuccess: async () => { setOpen(false); setForm({ name: '', description: '', reportTypeKey: '', schemaId: '', mode: 'append' }); await client.invalidateQueries({ queryKey: ['projects'] }); }, onError: (err) => setError(errorMessage(err)) });
  const toggle = useMutation({ mutationFn: async ({ id, active }: any) => api.patch(`/projects/${id}`, { active }), onSuccess: () => client.invalidateQueries({ queryKey: ['projects'] }) });
  return <><PageHeader title="整合專案" description="把資料來源、標準欄位、清洗、去重、整合與輸出設定保存成可重複執行的流程。" action={<button className="btn-primary" onClick={() => setOpen(true)}><Plus size={17} />建立專案</button>} />{projects.isLoading ? <Loading /> : !projects.data?.items.length ? <div className="card"><EmptyState icon={<FolderKanban />} title="尚無整合專案" description="先建立一個專案，再把每月銷售、庫存或自訂資料流程保存下來。" action={<button className="btn-primary" onClick={() => setOpen(true)}>建立第一個專案</button>} /></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.data.items.map((project: any) => <article className="card p-5" key={project.id}><div className="flex items-start justify-between"><div className="rounded-xl bg-brand-50 p-3 text-brand-700"><Workflow size={21} /></div><button title={project.active ? '停用' : '啟用'} className={`rounded-lg p-2 ${project.active ? 'text-emerald-600 hover:bg-emerald-50' : 'text-slate-400 hover:bg-slate-100'}`} onClick={() => toggle.mutate({ id: project.id, active: !project.active })}><Power size={18} /></button></div><h2 className="mt-5 text-lg font-black text-ink">{project.name}</h2><p className="mt-2 min-h-10 text-sm leading-5 text-slate-500">{project.description || '未填寫專案說明'}</p><div className="mt-5 grid grid-cols-2 gap-2 text-xs"><div className="rounded-lg bg-slate-50 p-2.5"><p className="text-slate-400">整合模式</p><p className="mt-1 font-bold text-slate-700">{modes.find((mode) => mode.value === project.mode)?.label ?? project.mode}</p></div><div className="rounded-lg bg-slate-50 p-2.5"><p className="text-slate-400">處理批次</p><p className="mt-1 font-bold text-slate-700">{project._count.jobs}</p></div></div><p className="mt-4 text-xs text-slate-400">欄位模板：{project.schema?.name ?? '依分析結果動態建立'}</p></article>)}</div>}
    {open && <Modal title="建立整合專案" onClose={() => setOpen(false)}>{error && <Notice type="error">{error}</Notice>}<form className="space-y-4" onSubmit={(e) => { e.preventDefault(); create.mutate(); }}><div><label className="label">專案名稱</label><input className="input" required minLength={2} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="例如：每月銷售整合" /></div><div><label className="label">說明</label><textarea className="input min-h-20" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><div><label className="label">整合模式</label><select className="input" value={form.mode} onChange={(e) => setForm({ ...form, mode: e.target.value })}>{modes.map((mode) => <option key={mode.value} value={mode.value}>{mode.label}</option>)}</select></div><div><label className="label">標準欄位模板</label><select className="input" value={form.schemaId} onChange={(e) => setForm({ ...form, schemaId: e.target.value })}><option value="">分析後決定</option>{schemas.data?.items.map((schema: any) => <option key={schema.id} value={schema.id}>{schema.name}</option>)}</select></div><button className="btn-primary w-full" disabled={create.isPending}>建立專案</button></form></Modal>}
  </>;
}
