import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, ClipboardCheck, EyeOff, Sparkles } from 'lucide-react';
import { api, errorMessage } from '../lib/api';
import { Confidence, EmptyState, Loading, Modal, Notice, PageHeader } from '../components/ui';

export function ReviewsPage() {
  const client = useQueryClient(); const [selected, setSelected] = useState<any>(null); const [targetKey, setTargetKey] = useState(''); const [apply, setApply] = useState(true); const [error, setError] = useState('');
  const reviews = useQuery({ queryKey: ['reviews'], queryFn: async () => (await api.get('/reviews')).data });
  const resolve = useMutation({ mutationFn: async ({ id, status }: { id: string; status: 'RESOLVED' | 'IGNORED' }) => api.patch(`/reviews/${id}`, { status, resolution: { sourceName: selected?.payload?.sourceName, targetKey: targetKey || selected?.payload?.targetKey, selectedType: targetKey || selected?.payload?.type }, applyToTemplate: apply }), onSuccess: async () => { setSelected(null); await client.invalidateQueries({ queryKey: ['reviews'] }); await client.invalidateQueries({ queryKey: ['dashboard'] }); }, onError: (err) => setError(errorMessage(err)) });
  return <><PageHeader title="待確認中心" description="分類、表頭、欄位與格式信心度不足時，系統會暫停自動合併並要求人工確認。" />
    <section className="card overflow-hidden">{reviews.isLoading ? <Loading /> : !reviews.data?.items.length ? <EmptyState icon={<ClipboardCheck />} title="沒有待確認項目" description="所有目前分析結果都高於自動處理門檻。" /> : <div className="divide-y divide-slate-100">{reviews.data.items.map((item: any) => <button key={item.id} className="flex w-full items-center gap-4 px-5 py-4 text-left transition hover:bg-slate-50" onClick={() => { setSelected(item); setTargetKey(item.payload?.targetKey ?? item.payload?.type ?? ''); }}><div className="rounded-xl bg-amber-50 p-3 text-amber-700"><Sparkles size={19} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-800">{item.title}</p><p className="mt-1 text-xs text-slate-400">{item.type} · {new Date(item.createdAt).toLocaleString('zh-TW')}</p></div><Confidence value={item.payload?.confidence} /></button>)}</div>}</section>
    {selected && <Modal title={selected.title} onClose={() => setSelected(null)}>{error && <Notice type="error">{error}</Notice>}<div className="rounded-xl bg-slate-50 p-4 text-sm"><p className="font-semibold text-slate-500">系統判斷</p><pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap break-words text-xs text-slate-700">{JSON.stringify(selected.payload, null, 2)}</pre></div><div className="mt-4"><label className="label">人工確認值</label><input className="input" value={targetKey} onChange={(e) => setTargetKey(e.target.value)} placeholder="例如：customer、sales 或表頭列號" /></div><label className="mt-4 flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={apply} onChange={(e) => setApply(e.target.checked)} />套用到後續相同欄位，形成映射規則</label><div className="mt-6 flex gap-3"><button className="btn-secondary flex-1" onClick={() => resolve.mutate({ id: selected.id, status: 'IGNORED' })}><EyeOff size={16} />忽略</button><button className="btn-primary flex-1" onClick={() => resolve.mutate({ id: selected.id, status: 'RESOLVED' })} disabled={!targetKey.trim()}><Check size={16} />確認並儲存</button></div></Modal>}
  </>;
}
